### ISSUE TITLE
Can not use two matchers in destination

### ISSUE THREAD

**Issue by daniel-blom** [unintended/download-organizer-chrome-extension#19]
When trying to use more than one matcher in destination this extension fails. 
Like this: site/{referrer:1}/{mime:1}/
or like this: site/{referrer:1}/{referrer:2}/

I am using Chromium 71.0.3578.98 and version 0.2.4 of the extension.

**Comment by rm-gthb** [comment]
Hello. I'm also faced a similar problem.

I [suggested ](https://github.com/unintended/download-organizer-chrome-extension/pull/20)the solution to the author and hope he will consider it in the near future.

**Comment by unintended** [comment]
Fixed in https://github.com/unintended/download-organizer-chrome-extension/pull/20
