### ISSUE TITLE
site/${referer:1}/ doesn't appear to work

### ISSUE THREAD

**Issue by Jakobud** [unintended/download-organizer-chrome-extension#23]
Just installed this. Looks nice. The default rule `site/${referer:1}/` does not appear to work. The file just gets dumped in my Downloads directory like normal. The rule is enabled and at the top. I disabled all other rules. Still doesn't work.

The other rules like for archives do seem to work fine.

I also tried to make my own rule for a specific site like this:

Referrer URL: .*cdn\.mywebsite\.com.*
Destination Path: mywebsite-downloads/

That also did not work. File just goes to the Downloads directory. What am I missing here?

**Comment by unintended** [comment]
it doesn't handle all cases, the idea is when you are at drive.google.com for example and press rightclick->download to a file, it will go to site/drive.google.com/filename.ext. I just checked and it works as expected

**Comment by unintended** [comment]
Give me more details to reproduce, please

**Comment by Jakobud** [comment]
I just downloaded a file from my google drive. The extension rule did not work. Here it is:

![screenshot_1](https://user-images.githubusercontent.com/87356/53999817-1cc62b00-4102-11e9-9f11-10022e089548.png)

**Comment by Jakobud** [comment]
I figured it out. You are using `referer` instead of `referrer` in your default rule. I just uninstalled and reinstalled the extension and it's still there. You should get that fixed because it's not gonna work out of the box.

**Comment by Jakobud** [comment]
https://github.com/unintended/download-organizer-chrome-extension/blob/727f8616b02b1c45af5092734ea6e6e547e92957/options.js#L10

**Comment by unintended** [comment]
This is perfect, thank you a lot!
