### ISSUE TITLE
Add support for referrer title

### ISSUE THREAD

**Issue by nibras-reeza** [unintended/download-organizer-chrome-extension#27]

**Comment by unintended** [comment]
I don't think it's possible, we can only use the fields of https://developers.chrome.com/extensions/downloads#type-DownloadItem

**Comment by nibras-reeza** [comment]
It might be possible to look up the title from a different request? Although I doubt this would be a clean solution. 

Many websites do not really have a meaningful URL or file name. 

For example, if you take bug tracking sites, they usually have only an ID in URL and nothing descriptive.

**Comment by unintended** [comment]
I got your intention, bot I don't want to extend the tool this way, it will require more premissions and will not be a clean solution as you mentioned.
