### ISSUE TITLE
HTML files save as images

### ISSUE THREAD

**Issue by Ptolemy2002** [unintended/download-organizer-chrome-extension#30]
When I try to save an HTML file (using the "save as" option in google chrome), it directs me to the image directory. Adding any rules doesn't seem to change this. Even if I disable all the rules that recognize images, it will still end up in the images directory.

Is this option supported? If so, how do I save html files in a specific location?

**Comment by unintended** [comment]
I assume that this is just your previous “save as” location. Try to disable the extension and you will get the same suggestion.
