### ISSUE TITLE
[FeatureRequest] Add option to control whether overwrite existing file

### ISSUE THREAD

**Issue by hiberabyss** [unintended/download-organizer-chrome-extension#32]

**Comment by B-iggy** [comment]
PLEASE! I support this FeatureRequest as some already implemented it in their extensions.

**Comment by unintended** [comment]
ok, I will add this when I have time

**Comment by B-iggy** [comment]
Awesome, thanks! I found the part for you already and tested it. You just have to make an option in the GUI please :)
https://github.com/unintended/download-organizer-chrome-extension/blob/master/manager.js#L110

There you change 'uniquify' to 'overwrite'.

**Comment by unintended** [comment]
soon will be released
