### ISSUE TITLE
PDF saving as TXT

### ISSUE THREAD

**Issue by KSJeff** [unintended/download-organizer-chrome-extension#47]
Hi there,

We're finding that with certain PDFs on certain websites the downloaded file gets converted to TXT from PDF.

### Rule
{ "enabled": true, "description": "EQ Training", "pattern": "Equinox/", "referrer": "training-equinox\\.kilburnstrode\\.com" },

### PDF downloading as TXT
Downloading item 
{bytesReceived: 0, canResume: false, danger: "safe", exists: true, fileSize: 36162, …}
bytesReceived: 0
canResume: false
danger: "safe"
exists: true
fileSize: 36162
filename: "Application filed - receipt.pdf"
finalUrl: "https://training-equinox.kilburnstrode.com/products/equinox/action_request_file.php?matterid=635930&documentid=305664&downloadFirefox=0"
id: 139
incognito: false
****mime: "text/plain"****
paused: false
referrer: "https://training-equinox.kilburnstrode.com/products/equinox/matters/m_documents.php?id=635930"
startTime: "2021-01-29T09:11:44.767Z"
state: "in_progress"
totalBytes: 36162
url: "https://training-equinox.kilburnstrode.com/products/equinox/matters/m_documents.php?id=635930"
__proto__: Object

### PDF downloading as PDF
Downloading item 
{bytesReceived: 0, canResume: false, danger: "safe", exists: true, fileSize: 886896, …}
bytesReceived: 0
canResume: false
danger: "safe"
exists: true
fileSize: 886896
filename: "Formal Drawings.PDF"
finalUrl: "https://training-equinox.kilburnstrode.com/products/equinox/action_request_file.php?matterid=635930&documentid=305724&downloadFirefox=0"
id: 138
incognito: false
****mime: "application/octet-stream"****
paused: false
referrer: "https://training-equinox.kilburnstrode.com/products/equinox/matters/m_documents.php?id=635930"
startTime: "2021-01-29T09:11:41.583Z"
state: "in_progress"
totalBytes: 886896
url: "https://training-equinox.kilburnstrode.com/products/equinox/matters/m_documents.php?id=635930"
__proto__: Object

### Or if this helps
`</training\-equinox\.kilburnstrode\.com(?:\/products\/equinox\/action_request_file\.php\?\*)?/>`

Do you have any ideas why this might be happening?

Thanks,

Jeff

**Comment by unintended** [comment]
I suppose it's the same issue as https://github.com/unintended/download-organizer-chrome-extension/issues/42

Although the filename of the first file contains ".pdf", the chrome's behavior is to override file extension from mime type (the server replies as 'text/plain'. The second one is defined by server as 'octet-stream', so Chrome uses .pdf as file extension from filename field. 

Actually, the download organizer doesn't (and cannot) affect Chrome's behavior at all in such cases.

**Comment by KSJeff** [comment]
Thanks for getting back to me. It turned out to be PHP server side config which we've fixed. Thanks for the awesome work :)

Jeff
