### ISSUE TITLE
why has the downloader folder be inside the default download folder?

### ISSUE THREAD

**Issue by michabbb** [unintended/download-organizer-chrome-extension#48]
I mean... this whole extension is useless for me if I am not able to choose "any" existing folder on my hard-drive.
is this a limitation of chrome or just something you @unintended decided on your own? ;)

thanks!

**Comment by unintended** [comment]
believe me, if it was possible I would made it :)
If you use mac/linux, you can try to make symlinks to destinations inside your Downloads folder and use them as connection points

**Comment by michabbb** [comment]
thanks for the quick response ;) here´s how it´s working for windows:

- set default download to "C:\"
- make some rules......
- make a default rule to the original download path: "C:\Users\.....\Download"

so everything works as before but with rules where i can use any folder on my disk 😏

**Comment by unintended** [comment]
I'm sure this approach would not pass any security audit, but ok :)

**Comment by gregbtm** [comment]
Was this ever figured out? I'd like PDFs to exclusively go to another folder on a totally separate drive. I'd like to keep everything else in the Downloads folder on my C drive.
