### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by amuagarwal** [unintended/download-organizer-chrome-extension#66]
Getting error with dates

Error handling response: ReferenceError: moment is not defined
    at chrome-extension://oamembonjndgangicfphlckkdmagpjlg/manager.js:78:25
    at String.replace (<anonymous>)
    at chrome-extension://oamembonjndgangicfphlckkdmagpjlg/manager.js:75:44
    at Array.every (<anonymous>)
    at chrome-extension://oamembonjndgangicfphlckkdmagpjlg/manager.js:42:18
    at chrome-extension://oamembonjndgangicfphlckkdmagpjlg/manager.js:44:17
    at Array.every (<anonymous>)
    at chrome-extension://oamembonjndgangicfphlckkdmagpjlg/manager.js:42:18

**Comment by ni1chigo2115** [comment]
same

**Comment by amuagarwal** [comment]
till the time not get updated i rolledback to 0.3.2

**Comment by unintended** [comment]
fixed in 0.4.1
