### ISSUE TITLE
"Name confliction action" details in help

### ISSUE THREAD

**Issue by mikedidomizio** [unintended/download-organizer-chrome-extension#71]
Great extension.

Is there value in detailing in the Help section the different Name conflict actions?
I'm a software engineer myself but wanted to truly understand what "uniquify" meant.

For those that don't know, it's stated [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/FilenameConflictAction) and will just append `(1)` to the filename, and increment if you keep trying to download the same file.

I think the Help section is great and would benefit to also include that information as well.

Thanks

**Comment by unintended** [comment]
You're welcome to make a PR with the changes
